### PR TITLE
rc.yml: Provide cargo_{fetch,build,install,test} macros

### PR DESCRIPTION
**Pull request by joebonrichie**
For setup, build, install and check steps respectively.

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
Perhaps you could have it automatically pull in cargo as a builddep?

**Comment by ReillyBrogan** [comment]
So that's not actually possible, I was getting it confused with boulder.

**Review by ReillyBrogan — APPROVED** [review]

**Review by ermo — CHANGES_REQUESTED** [review]
Let's mirror the macros just landed in Serpent here for consistency?

cf. https://github.com/serpent-os/boulder/blob/main/data/macros/actions/cargo.yml

**Review by ermo — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
